### ISSUE TITLE
Todo to ship

### ISSUE THREAD

**Issue by bordoley** [bordoley/reactive-js#5]
- [x] disposables unit tests
- [ ] dom unit tests
- [ ] ix-core unit tests
- [x] rx-core unit tests
- [x] rx-imperative unit tests
- [x] rx-observables unit tests
- [x] rx-operators unit tests
- [ ] state-container unit tests

- [x] react example project

- [x] disposables readme
- [x] dom readme
- [x] eventloop-scheduler readme
- [x] ix-core readme
- [x] react-dom-router readme
- [x] react-hooks readme
- [x] react-router readme
- [x] react-scheduler readme
- [x] rx-core readme
- [x] rx-imperative readme
- [x] rx-observables readme
- [x] rx-operators readme
- [x] scheduler readme
- [x] state-container unit tests
- [x] virtualtime-scheduler readme
- [ ] readme
